# This file was created by the flash_writer_tool.sh
BOARD=rzv2n-sr-som
BOARD_VERSION=
FLASH=0
SERIAL_DEVICE_INTERFACE=/dev/ttyUSB0
SERIAL_DEVICE_SPEED=115200
FILES_DIR=.
FW_PREBUILT=
#FLASHWRITER=./Flash_Writer_SCIF_RZV2N_EVK_LPDDR4X.mot
FLASHWRITER=./Flash_Writer_SCIF_RZV2N_SR_SOM_8GB_LPDDR4X.mot
FIP=1
EMMC_4BIT=0
SA0_FILE=
BL2_FILE=./bl2_bp_spi-rzv2n-sr-som.srec
SA6_FILE=
BL31_FILE=
FIP_FILE=./fip-rzv2n-sr-som.srec
UBOOT_FILE=
