# This file was created by the flash_writer_tool.sh
BOARD=rzv2n-sr-som
FLASH=1
SERIAL_DEVICE_INTERFACE=/dev/ttyUSB0
SERIAL_DEVICE_SPEED=115200
FILES_DIR=.
FLASHWRITER=./Flash_Writer_SCIF_RZV2N_EVK_LPDDR4X.mot
FIP=1
EMMC_4BIT=0
BL2_FILE=./bl2_bp_mmc-rzv2n-sr-som.srec
FIP_FILE=./fip-rzv2n-sr-som.srec
LONGER_CMD_DELAY=2.5
